name: "Deploy to Server"

on:
  push:
    branches:
      - main
pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}

    steps:
      - uses: actions/checkout@v3

      - name: "Build Docker Image"
        run: |
          docker login -u lilielise -p $DOCKERHUB_PAT
          docker build -t lilielise/mywebsite .
          docker push lilielise/mywebsite
        env:
          DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

      - name: "Configure SSH"
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: "Put SSH Key in place for Server Access"
        run: |
          touch pem.pem
          echo $SSH_KEY64 | base64 -d > pem.pem && chmod 400 pem.pem
          ssh-keygen -R $SERVER_IP
        env:
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}

      - name: "Docker Pull and Restart Container"
        run: |
          ssh -o StrictHostKeyChecking=no -i pem.pem ubuntu@$SERVER_IP 'docker pull lilielise/mywebsite'
          ssh -o StrictHostKeyChecking=no -i pem.pem ubuntu@$SERVER_IP 'docker stop mysite && docker rm mysite'
          ssh -o StrictHostKeyChecking=no -i pem.pem ubuntu@$SERVER_IP 'docker run --name mysite -p 80:80 -d lilielise/mywebsite'
